version: "3.8"

services:
   backend:
      build: .
      image: backend
      command: npm run start:dev
      volumes:
         - .:/usr/app
      ports:
         - ${PORT}:${PORT}
      links:
         - db
         - minio
   backend_tester:
      image: backend
      command: npm run test:dev
      environment:
         DB_NAME: flora
         DB_HOST: db
         DB_USER: flora_adm
         DB_PASS: segredo99
         DB_PORT: 5432
      volumes:
         - .:/usr/app
      links:
         - backend
         - db
         - minio
   db:
      image: postgres
      environment:
         POSTGRES_PASSWORD: ${DB_PASS}
         POSTGRES_USER: ${DB_USER}
         POSTGRES_DB: ${DB_NAME}
      volumes:
         - ./pgdata:/var/lib/postgresql/data
      ports:
         - ${DB_PORT}:${DB_PORT}
   minio:
      image: minio/minio:latest
      environment:
         MINIO_ROOT_USER: ${MINIO_USER}
         MINIO_ROOT_PASSWORD: ${MINIO_PASS}
      command: minio server /var/lib/minio/data
      volumes:
         - ./miniodata:/var/lib/minio/data
      ports:
         - ${MINIO_PORT}:${MINIO_PORT}